### ISSUE TITLE
Проект не запускается

### ISSUE THREAD

**Issue by olegromashin** [Oppai-Dragon/bot#3]
При запуске получаю такое сообщение:

> [ERROR] /home/oleg/Development/Haskell/Projects/FSD/bot\src\Config.json: openBinaryFile: does not exist (No such file or directory)
	Called at src/Config/Set.hs 27:7-27:38 in Config.Set

Конфиг лежит где надо, если что.
Кроме этого, после такого надо завершать программу.

**Comment by Oppai-Dragon** [comment]
Сделал, чтобы после критических ошибок бот закрывался. Не уверен с чем связаны эти ошибки.

**Comment by Oppai-Dragon** [comment]
Исправил. На винде писал абсолютный путь, хотя можно было, как я теперь понял, и не парится с этим. В итоге он искал путь  /home/oleg/Development/Haskell/Projects/FSD/bot\src\Config.json в папке /bot.
