### ISSUE TITLE
Имена функций логирования

### ISSUE THREAD

**Issue by olegromashin** [Oppai-Dragon/bot#6]
Непонятно, почему решил добавить букву M в конце функций логирования. Имена не отражают своего назначения.
errorMonad? - ошибка в монаде?
errorMessage? - больше похоже сущность, которая содержит в себе ошибку. имя не указывает на то, что оно выполняет какое-то действие
Можно сделать что-то вроде logError или writeError.

**Comment by Oppai-Dragon** [comment]
Согласен. Когда только начинал делать логирование насмотрелся статей и набрал оттуда имён.
